[build]
    publish     = "dist"
    functions   = "netlify/functions"
    command     = "npm run build"

[dev]
    autoLaunch  = true

    # netlify server port
    port = 5555
    # targetPort = 5555

# [[edge_functions]]
#  function = "index"
#  path = "/*"

[functions]
    external_node_modules = ["express"]
    node_bundler = "esbuild"
    
#    [functions.hello]
#        included_files = ["templates/hello.hbs"]

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "http://localhost:5555"

# redirects not needed in Netlify v2.0
# [[redirects]]
    # from        = "/hello"
    # to          = "/.netlify/functions/hello"
    # status      = 200
    # force       = true

    # force = true set in redirect to send all requests to your function even if content is not found.
    # As my root directory (public) has a index.html file, this file is served first without the 'force'
    # setting to true.